export const actionType = {
  FEATH_PRODUCT: 'FEATH_PRODUCT',
  SET_PRODUCTS : 'SET_PRODUCTS',
  SELECTED_PRODUCTS : 'SELECTED_PRODUCTS',
  REMOVE_SELECTED_PRODUCTS : 'REMOVE_SELECTED_PRODUCTS',
  ADDCART_PRODUCT: 'ADDCART_PRODUCT',
  SELECT_PRODUCT_REMOVE: 'SELECT_PRODUCT_REMOVE',
  REMOVE_ADD_PRODUCT: 'REMOVE_ADD_PRODUCT',
  BYU_PRODUCT: 'BYU_PRODUCT',
  BYU_PRODUCT_CART: 'BYU_PRODUCT_CART'
}
